### ISSUE TITLE
Playlist Length 

### ISSUE THREAD

**Issue by byrnes** [jordam/Portify.JS#5]
Playlists can't be over 1000 songs, but portify keeps adding them regardless. There should be an option to check for this or to split them.

**Comment by jordam** [comment]
@ConnorB123 Good catch.

Its not perfect, but I've added something to split up playlists over 1000 tracks. Its going to get the track list from spotify, split it up into playlists of < 1000 tracks, create the empty playlists, and then search for and add these tracks to the playlists.

The obvious gotcha is when some of the 1000 tracks arent found on google music the final playlist will be less then 1000 tracks.

I imported a 1466 track playlist with portify.js and the resulting playlists were 923 songs and 436 songs. Not the cleanest result, I'd prefer 1000/359, but due to the nature of the program (its not really confirming anything) its a good balance between effort and functionality.

Thanks for the input, I didn't have any 1000+ playlists personally.
