### ISSUE TITLE
Cool project but it doesn't work 

### ISSUE THREAD

**Issue by rignaneseleo** [jordam/Portify.JS#6]
I try it on mozilla and on chrome.

On firefox it seems work but when it has finished there are only empty playlists.

On chrome it load spotify but I don't understand what do after copy the oauth code.. I return to google music page and clicked the script as written in your description but it load always spotify!

Btw it is a cool project, compliments!

**Comment by jordam** [comment]
Thanks, but you appear to be trying to use the Firefox/other browser instructions with the chrome version. The chrome version is different, don't copy or touch any button except for the bookmark. Just keep pressing the bookmark and it will perform every step for you one by one. It is going back to spotify because the script wants to do that step, it doesn't want you to do it yourself.

As per it glitching out in Firefox I'm going to have to run some tests when I get a sec. I'm not usually in Firefox.

**Comment by jordam** [comment]
It appears to be working in firefox on my end.

**Comment by jordam** [comment]
Seems to be working. Closing until further comment.
